import { Code2, QrCode, MonitorCog, Hotel, Palette, TrendingUp, ShieldCheck, type LucideIcon } from "lucide-react";
import developer from "@/assets/software-developer.jpg.asset.json";
import qr from "@/assets/qr-menu-table.jpg.asset.json";
import computers from "@/assets/computers-desktop.png.asset.json";
import pos from "@/assets/pos-terminal.webp.asset.json";
import design from "@/assets/design-icon.png.asset.json";
import growth from "@/assets/digital-growth-customers.jpg.asset.json";
import security from "@/assets/access-control.webp.asset.json";
import camera from "@/assets/security-camera.jpg.asset.json";

export type ContentItem = { title: string; description: string };
export type ContentSection = { title: string; body?: string | undefined; items: readonly ContentItem[] };
export type ProcessStep = { title: string; description: string };
export type ServiceContent = {
  eyebrow: string; title: string; heroDescription: string; introTitle: string; introBody: string;
  sections: readonly ContentSection[]; audienceTitle: string; audiences: readonly string[]; process: readonly ProcessStep[];
  benefits: readonly ContentItem[]; faqs: readonly (readonly [string, string])[]; heroCta: string; finalHeading: string;
  finalTitle: string; finalBody: string; primaryCta: string; secondaryCta: string; iconKey: IconKey;
};
export type IconKey = "code" | "qr-code" | "computer" | "hotel" | "palette" | "growth" | "security";
export const serviceIcons: Record<IconKey, LucideIcon> = { code: Code2, "qr-code": QrCode, computer: MonitorCog, hotel: Hotel, palette: Palette, growth: TrendingUp, security: ShieldCheck };

const sharedCta = {
  finalHeading: "Have a project in mind?", finalTitle: "Let's build the right technology solution for your business.",
  finalBody: "Tell us what you need and let's discuss how Ikelex Technology can help.", primaryCta: "Start a Project", secondaryCta: "Contact Us",
};

export const services = [
  {
    slug: "app-software-development", legacySlugs: ["software-development"], title: "App & Software Development", icon: Code2, short: "Purpose-built digital products for demanding workflows.", image: developer.url, imageAlt: "Software developer working at a computer",
    content: { eyebrow: "Software engineering", title: "Custom Software & App Development", heroDescription: "We build digital products that help businesses work smarter, automate operations, and deliver better customer experiences. From business management platforms to web applications and mobile apps, Ikelex Technology develops software tailored to your business requirements.", heroCta: "Start a Project", introTitle: "What We Do", introBody: "We design and develop custom software solutions for businesses that need technology built around the way they actually operate. Whether you need a customer-facing application, internal business software, an online platform, or a complete digital system, we turn your requirements into functional and scalable technology.",
      sections: [{ title: "Our Software Development Services", items: [
        { title: "Custom Business Software", description: "Software designed around your company's specific processes, workflows and operational requirements." },
        { title: "Web Application Development", description: "Modern, responsive web applications that work across desktop, tablet and mobile devices." },
        { title: "Mobile App Development", description: "Mobile applications designed to give customers and businesses convenient access to digital services." },
        { title: "Business Automation", description: "Digital systems that reduce repetitive manual processes and improve operational efficiency." },
        { title: "Custom Dashboards", description: "Centralized dashboards for viewing business information, monitoring activities and managing operations." },
        { title: "System Integration", description: "Connecting different business systems and digital tools so information can move efficiently between them." },
      ] }], audienceTitle: "Who Is It For?", audiences: ["Startups", "Hotels", "Restaurants", "Retail businesses", "Corporate organizations", "Service businesses", "Growing businesses", "Organizations with manual processes"],
      process: [{ title: "Discovery", description: "We understand your business and requirements." }, { title: "Planning", description: "We define the features, structure and technology needed." }, { title: "Design", description: "We create the user experience and interface." }, { title: "Development", description: "We build and integrate the system." }, { title: "Testing", description: "We test functionality, usability and performance." }, { title: "Deployment & Support", description: "We launch the solution and provide ongoing support where required." }], benefits: [],
      faqs: [["Can you build software specifically for my business?", "Yes. Our software development service can be tailored around your business requirements and workflow."], ["Can you develop both web and mobile applications?", "Yes. Projects can be developed for web, mobile or both depending on the requirements."], ["Can you integrate existing systems?", "Yes, where the existing systems provide the necessary integration capabilities."], ["Can you maintain software after development?", "Ongoing maintenance and technical support can be arranged depending on the project."]], iconKey: "code", ...sharedCta },
  },
  {
    slug: "qr-code-digital-menu", legacySlugs: ["qr-digital-menu"], title: "QR Code Digital Menu", icon: QrCode, short: "Elegant, easy-to-update menu experiences for hospitality teams.", image: qr.url, imageAlt: "QR menu card on a restaurant table",
    content: { eyebrow: "Hospitality experience", title: "Turn Your Menu Into a Digital Experience", heroDescription: "Give customers a faster, cleaner and more convenient way to explore your menu using QR technology. Ikelex Technology creates digital QR menus for restaurants, hotels, lounges, bars and food businesses.", heroCta: "Create a Digital Menu", introTitle: "What Is a QR Digital Menu?", introBody: "A QR digital menu allows customers to scan a QR code using their smartphone and instantly access your business menu. Instead of depending entirely on printed menus, businesses can provide customers with a digital menu that is accessible directly from their phones.",
      sections: [{ title: "What We Provide", items: [{ title: "Digital Menu Design", description: "Professionally structured digital menus designed around your brand." }, { title: "QR Code Integration", description: "Customers can scan a QR code to access your menu." }, { title: "Mobile-Friendly Experience", description: "Menus are designed to work comfortably on smartphones." }, { title: "Menu Categories", description: "Organize food, drinks and other offerings into clear categories." }, { title: "Menu Updates", description: "Digital menus can make it easier to update information without repeatedly redesigning printed materials." }, { title: "Branding", description: "Your menu can reflect your business identity, colors, images and presentation style." }] }],
      audienceTitle: "Perfect For", audiences: ["Restaurants", "Hotels", "Lounges", "Bars", "Cafés", "Fast-food businesses", "Food vendors", "Event food businesses"], process: [{ title: "Scan", description: "Customer scans the QR code." }, { title: "Open", description: "The digital menu opens on their phone." }, { title: "Browse", description: "They explore your menu and available items." }, { title: "Choose", description: "They can review the information before ordering through your chosen ordering process." }], benefits: [],
      faqs: [["Do customers need an app?", "The digital menu can be accessed through a smartphone browser after scanning the QR code."], ["Can I update my menu?", "Yes, digital menus are designed to make menu management and updates easier."], ["Can I use my own food pictures?", "Yes. You can provide your menu images and other visual assets."], ["Is it suitable for hotels and lounges?", "Yes. QR menus can be used across restaurants, hotels, lounges, bars and other food businesses."]], iconKey: "qr-code", ...sharedCta },
  },
  {
    slug: "computers-it-services", legacySlugs: [], title: "Computers & IT Services", icon: MonitorCog, short: "Reliable devices, setup, maintenance and practical support.", image: computers.url, imageAlt: "White desktop computer with keyboard and mouse",
    content: { eyebrow: "Workplace technology", title: "Computers, Accessories & IT Services", heroDescription: "Technology products and technical services to keep your business connected and productive. Ikelex Technology provides computer products, accessories and related IT services for businesses and individuals.", heroCta: "Start a Project", introTitle: "Business Technology Setup", introBody: "We can help businesses set up the technology required for their daily operations, including computers, software, accessories, business applications, network-related technology and security systems.",
      sections: [{ title: "What We Offer", items: [{ title: "Computers & Laptops", description: "Technology equipment for work, business and everyday computing needs." }, { title: "Computer Accessories", description: "Essential accessories and peripherals for your setup." }, { title: "Software Installation", description: "Installation and configuration of required software." }, { title: "System Setup", description: "Assistance with setting up computers and technology systems." }, { title: "IT Support", description: "Technical assistance for common computer and technology requirements." }] }, { title: "Why Professional IT Support Matters", body: "Reliable technology helps businesses reduce interruptions, improve productivity and ensure employees have the tools they need to work effectively.", items: [] }], audienceTitle: "Who We Serve", audiences: ["Individuals", "Startups", "Small businesses", "Hotels", "Restaurants", "Offices", "Corporate organizations", "Retail businesses"], process: [], benefits: [],
      faqs: [["Do you sell computers and accessories?", "Yes."], ["Can you install software?", "Yes."], ["Can you help set up computers for an office?", "Yes, depending on the requirements of the project."], ["Do you provide technical support?", "Yes, IT support services can be provided for supported technology requirements."]], iconKey: "computer", ...sharedCta },
  },
  {
    slug: "hotel-pos-inventory", legacySlugs: [], title: "Hotel, POS & Inventory Software", icon: Hotel, short: "Connected operations from reservations and billing to stock control.", image: pos.url, imageAlt: "Touchscreen point-of-sale terminal",
    content: { eyebrow: "Operational systems", title: "One Technology Platform for Your Business Operations", heroDescription: "Manage bookings, billing, sales and inventory with software designed for hotels, shops, lounges and restaurants. Ikelex Technology provides business management software designed to help businesses organize their daily operations digitally.", heroCta: "Start a Project", introTitle: "What It Does", introBody: "Instead of managing important business information across notebooks, spreadsheets and disconnected systems, businesses can use software to centralize their operations.",
      sections: [{ title: "Hotel Management", body: "Manage important hotel operations such as:", items: ["Booking management", "Guest information", "Billing", "Room-related records", "Transaction management", "Operational reporting"].map((title) => ({ title, description: "" })) }, { title: "POS Management", body: "For shops, restaurants and lounges:", items: ["Sales transactions", "Billing", "Product management", "Transaction records", "Sales monitoring", "Business reporting"].map((title) => ({ title, description: "" })) }, { title: "Inventory Management", body: "Keep better track of products and stock. Features can include:", items: ["Inventory records", "Stock tracking", "Product management", "Stock movement", "Sales-related inventory updates", "Inventory reporting"].map((title) => ({ title, description: "" })) }],
      audienceTitle: "Who Is It For?", audiences: ["Hotels — manage bookings, billing and operational information", "Restaurants — manage sales, products and transactions", "Lounges — manage sales and business operations", "Shops — manage products, sales and inventory"], process: [], benefits: [{ title: "Better Organization", description: "Keep important operational information in one system." }, { title: "Improved Visibility", description: "Access useful information about business activity." }, { title: "Reduced Manual Work", description: "Digitize repetitive operational processes." }, { title: "Better Record Keeping", description: "Maintain structured business records." }],
      faqs: [["Can the system be used by restaurants?", "Yes."], ["Can it manage inventory?", "Yes."], ["Can it manage hotel bookings?", "The hotel management functionality is designed to support booking management."], ["Can the system be customized?", "Requirements can be discussed to determine the appropriate configuration or customization."]], iconKey: "hotel", ...sharedCta },
  },
  {
    slug: "graphics-design-branding", legacySlugs: ["branding-design"], title: "Graphics Design & Branding", icon: Palette, short: "Identity and communication systems designed for recognition and trust.", image: design.url, imageAlt: "Digital design illustration",
    content: { eyebrow: "Brand systems", title: "Build a Brand People Remember", heroDescription: "Creative design and branding solutions that help businesses communicate professionally and consistently. Ikelex Technology provides graphics, branding, UI/UX and product design services.", heroCta: "Start a Project", introTitle: "What We Do", introBody: "We create clear visual systems and digital experiences that help businesses present themselves with consistency and purpose.",
      sections: [{ title: "Creative & Digital Design", items: [{ title: "Brand Identity", description: "Develop a consistent visual identity for your business." }, { title: "Logo Design", description: "Create professional logos that represent your brand." }, { title: "Marketing Graphics", description: "Design visual materials for campaigns, promotions and business communication." }, { title: "Social Media Design", description: "Create branded graphics for digital platforms." }, { title: "UI/UX Design", description: "Design user interfaces and experiences for websites, applications and digital products." }, { title: "Product Design", description: "Turn digital product ideas into structured, user-friendly interfaces." }] }, { title: "Brand Materials", body: "Depending on the project, design work can include:", items: ["Logos", "Business cards", "Flyers", "Posters", "Social media graphics", "Marketing materials", "Presentation graphics", "Digital product interfaces", "UI/UX designs"].map((title) => ({ title, description: "" })) }], audienceTitle: "Designed for real use", audiences: ["Businesses building a new identity", "Teams refreshing an existing brand", "Digital products needing a clear interface", "Campaigns requiring consistent visual assets"],
      process: [{ title: "Understand", description: "We understand your business and audience." }, { title: "Concept", description: "We develop the creative direction." }, { title: "Design", description: "We create the visual solution." }, { title: "Refine", description: "We make revisions based on feedback." }, { title: "Deliver", description: "We prepare the final design assets." }], benefits: [],
      faqs: [["Can you create a complete brand identity?", "Yes."], ["Do you design social media graphics?", "Yes."], ["Do you design websites and app interfaces?", "Yes, through our UI/UX and product design services."], ["Can I provide my own brand guidelines?", "Yes. Existing brand guidelines can be incorporated into the design work."]], iconKey: "palette", ...sharedCta },
  },
  {
    slug: "digital-growth", legacySlugs: [], title: "Digital Growth & Online Presence", icon: TrendingUp, short: "Digital visibility and campaigns built around clear priorities.", image: growth.url, imageAlt: "Customers engaging with a digital experience on a laptop",
    content: { eyebrow: "Digital presence", title: "Grow Your Business Online", heroDescription: "Build a stronger digital presence and make it easier for customers to discover your business online. Ikelex Technology provides digital growth services covering search visibility, business listings and online advertising.", heroCta: "Start a Project", introTitle: "Why Your Online Presence Matters", introBody: "Customers increasingly use search engines and online platforms to discover businesses, compare services and find contact information. A properly structured digital presence can make your business easier to discover and understand.",
      sections: [{ title: "What We Do", items: [{ title: "SEO", description: "Improve the structure and discoverability of your website for search engines." }, { title: "Google Business Profile Setup", description: "Help establish and optimize your business presence on Google." }, { title: "Google Ads", description: "Set up and manage paid advertising campaigns where appropriate." }, { title: "Meta Ads", description: "Manage advertising campaigns across Meta platforms." }, { title: "Online Presence Strategy", description: "Help businesses organize their digital presence across relevant online channels." }] }], audienceTitle: "Suitable For", audiences: ["Local businesses", "Restaurants", "Hotels", "Startups", "Retail businesses", "Service providers", "Growing companies"],
      process: [{ title: "Audit", description: "Review your existing digital presence." }, { title: "Strategy", description: "Identify opportunities and define priorities." }, { title: "Setup", description: "Configure the required digital platforms." }, { title: "Optimization", description: "Improve content, profiles and campaigns." }, { title: "Monitor", description: "Review performance and make adjustments." }], benefits: [],
      faqs: [["Can you set up a Google Business Profile?", "Yes."], ["Do you provide SEO?", "Yes."], ["Do you manage Google Ads?", "Yes."], ["Do you manage Meta Ads?", "Yes."], ["Can you work with an existing website?", "Yes, where the existing website can support the required improvements."]], iconKey: "growth", ...sharedCta },
  },
  {
    slug: "it-security-solutions", legacySlugs: ["it-security"], title: "IT Systems & Security Solutions", icon: ShieldCheck, short: "Practical protection, access control and resilient infrastructure.", image: security.url, secondaryImage: camera.url, imageAlt: "Fingerprint access-control system",
    content: { eyebrow: "Systems and security", title: "Secure, Connected & Reliable IT Systems", heroDescription: "Technology infrastructure and security solutions designed to support modern business environments. Ikelex Technology provides IT systems and security-related services for businesses and organizations.", heroCta: "Start a Project", introTitle: "Security Systems", introBody: "Businesses can use technology to improve visibility and control across their premises. Possible solutions include CCTV cameras, monitoring systems, access control, computer systems and supporting IT equipment.",
      sections: [{ title: "What We Do", items: [{ title: "CCTV Systems", description: "Installation and setup of CCTV systems for monitoring business premises." }, { title: "Access Control", description: "Technology solutions designed to help manage and control access to designated areas." }, { title: "Software Installation", description: "Installation and configuration of required software." }, { title: "Computer Accessories", description: "Technology accessories and equipment for business environments." }, { title: "IT System Setup", description: "Help with setting up technology systems according to business requirements." }] }], audienceTitle: "Who Needs These Solutions?", audiences: ["Offices", "Hotels", "Restaurants", "Shops", "Warehouses", "Corporate facilities", "Residential/commercial premises"],
      process: [{ title: "Assess", description: "Understand the environment and requirements." }, { title: "Plan", description: "Determine the appropriate technology solution." }, { title: "Install", description: "Deploy the required systems." }, { title: "Configure", description: "Configure the systems for operation." }, { title: "Support", description: "Provide technical assistance where required." }], benefits: [],
      faqs: [["Do you install CCTV systems?", "Yes."], ["Do you provide access-control solutions?", "Yes."], ["Can you install software on computers?", "Yes."], ["Can you help businesses choose IT equipment?", "Yes, depending on the requirements."]], iconKey: "security", ...sharedCta },
  },
] as const;

export type Service = (typeof services)[number];
export const processSteps = ["Discover", "Plan", "Build", "Launch & Support"];
export const serviceBySlug = (slug: string) => services.find((service) => service.slug === slug || service.legacySlugs.some((legacy) => legacy === slug));
export const globalFaqs = [
  { category: "Working together", question: "What kinds of businesses does Ikelex work with?", answer: "Ikelex works around the operational need rather than a fixed company type. The first conversation establishes fit, priorities, and scope." },
  { category: "Working together", question: "How does a project begin?", answer: "Projects begin with a focused discussion about the business need, current workflow, desired outcome, and practical constraints." },
  { category: "Pricing", question: "How much does a project cost?", answer: "Pricing is prepared after the scope, users, integrations, hardware, and delivery requirements are understood. Contact Ikelex for a tailored quote." },
  { category: "Pricing", question: "Are there fixed packages?", answer: "Not currently. Ikelex recommends the right scope for the requirement instead of publishing placeholder packages." },
  { category: "Delivery", question: "Can Ikelex improve an existing system?", answer: "Yes. Existing products, processes, websites, and infrastructure can be assessed before a recommended improvement path is agreed." },
  { category: "Delivery", question: "Is support available after launch?", answer: "Support expectations are agreed during planning and can cover launch assistance, maintenance, and future improvement." },
  { category: "Security", question: "How is private business information handled?", answer: "Access and data handling are limited to what the work requires, with suitable technical controls defined for the solution." },
];