import { createFileRoute } from "@tanstack/react-router";
import { Reveal, SectionHeading } from "@/components/ikelex";
import { services } from "@/lib/site-data";
import core from "@/assets/digital-core.jpg";

export const Route = createFileRoute("/about")({
  head: () => ({ meta: [{ title: "About Ikelex Technology" }, { name: "description", content: "Meet Ikelex Technology: a business-first team building practical software, digital products and IT systems." }, { property: "og:title", content: "About Ikelex Technology" }, { property: "og:description", content: "We use technology to solve real business problems." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: About,
});

function About() { return <div className="pt-28">
  <section className="relative min-h-[72svh] overflow-hidden px-6 py-24"><div className="absolute inset-0 ikelex-grid opacity-20"/><div className="relative mx-auto grid max-w-7xl items-end gap-12 lg:grid-cols-[1.15fr_.85fr]"><Reveal><p className="text-xs font-bold uppercase text-accent">About Ikelex Technology</p><h1 className="mt-7 text-balance text-5xl font-semibold uppercase leading-[.9] sm:text-8xl">We use technology to solve real business problems.</h1></Reveal><Reveal delay={.2}><img src={core} alt="Connected business systems" className="aspect-square w-full rounded-full object-cover"/></Reveal></div></section>
  <section className="bg-ikelex-white py-28 text-ikelex-navy-2"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Who we are" title="Clarity before complexity." copy="Ikelex Technology designs and builds digital systems around what a business genuinely needs. We combine software thinking, visual craft and practical infrastructure so technology supports the work instead of getting in its way."/><div className="mt-20 grid gap-px bg-ikelex-navy/15 md:grid-cols-3">{[["Who we are","A technology partner focused on useful, considered outcomes."],["What we do","Build products, systems, brands and digital infrastructure."],["How we work","Understand the operation, shape the right solution, then deliver with care."]].map(([t,c])=><Reveal key={t} className="bg-ikelex-white p-8"><h3 className="text-2xl font-semibold uppercase">{t}</h3><p className="mt-5 leading-7 text-ikelex-navy/65">{c}</p></Reveal>)}</div></div></section>
  <section className="py-28"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Capabilities" title="One team. Connected disciplines."/><div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.slice(0,6).map((s,i)=>{const Icon=s.icon;return <Reveal key={s.slug} delay={i*.05} className="border border-border bg-card p-7"><Icon className="size-7 text-accent"/><h3 className="mt-16 text-2xl font-semibold uppercase">{s.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{s.short}</p></Reveal>})}</div></div></section>
  <section className="bg-ikelex-navy py-28"><div className="mx-auto grid max-w-7xl gap-5 px-6 lg:grid-cols-2">{[["Our mission","To turn real business needs into clear, dependable technology that improves how people work and serve."],["Our vision","A future where practical digital systems help ambitious businesses operate with greater confidence."]].map(([t,c],i)=><Reveal key={t} delay={i*.1} className="group min-h-96 border border-border bg-card p-9 transition-transform duration-500 hover:-translate-y-2"><p className="text-xs font-bold uppercase text-accent">{t}</p><p className="mt-28 text-3xl font-medium leading-tight sm:text-5xl">{c}</p></Reveal>)}</div></section>
</div> }