import { createFileRoute, Link } from "@tanstack/react-router";
import { Search, ArrowUpRight } from "lucide-react";
import { useMemo, useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Reveal, SectionHeading } from "@/components/ikelex";
import { globalFaqs } from "@/lib/site-data";

export const Route = createFileRoute("/faq")({ head: () => ({ meta: [{ title: "Frequently Asked Questions — Ikelex Technology" }, { name: "description", content: "Answers about Ikelex Technology services, project delivery, pricing and support." }, { property: "og:title", content: "Frequently Asked Questions — Ikelex Technology" }, { property: "og:description", content: "Clear answers about working with Ikelex Technology." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: FAQPage });
function FAQPage() { const categories = ["All", ...new Set(globalFaqs.map((item) => item.category))]; const [category, setCategory] = useState("All"); const [search, setSearch] = useState(""); const items = useMemo(() => globalFaqs.filter((item) => (category === "All" || item.category === category) && `${item.question} ${item.answer}`.toLowerCase().includes(search.toLowerCase())), [category, search]); return <div className="pt-28"><section className="px-6 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="eyebrow">Knowledge centre</p><h1 className="mt-7 max-w-5xl text-balance text-6xl font-semibold uppercase leading-[.9] sm:text-8xl">Questions, answered clearly.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground">Find practical answers about scope, pricing, delivery, support and security.</p></Reveal></div></section><section className="border-t border-border bg-surface-soft py-24"><div className="mx-auto max-w-5xl px-6"><div className="relative"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Search frequently asked questions" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search questions" className="h-14 bg-background pl-12"/></div><div className="mt-5 flex flex-wrap gap-2" role="group" aria-label="FAQ categories">{categories.map((item) => <Button key={item} size="sm" variant={category === item ? "default" : "outline"} onClick={() => setCategory(item)}>{item}</Button>)}</div><div className="mt-12"><SectionHeading eyebrow={`${items.length} answers`} title="What would you like to know?"/><Accordion type="single" collapsible className="mt-12 border-y border-border">{items.map((item, index) => <AccordionItem key={item.question} value={`item-${index}`}><AccordionTrigger className="text-left text-lg font-semibold">{item.question}</AccordionTrigger><AccordionContent className="max-w-3xl text-base leading-8 text-muted-foreground">{item.answer}</AccordionContent></AccordionItem>)}</Accordion>{!items.length && <div className="mt-10 border border-dashed border-border p-10 text-center"><p className="text-muted-foreground">No matching answer found.</p><Button variant="link" asChild><Link to="/contact">Ask Ikelex directly <ArrowUpRight/></Link></Button></div>}</div></div></section></div>; }
