import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight } from "lucide-react";
import { ParallaxImage, StaggerChildren, StaggerItem } from "@/components/animation-primitives";
import { Reveal, SectionHeading } from "@/components/ikelex";
import { services } from "@/lib/site-data";
import banner from "@/assets/technology-banner.jpg.asset.json";

export const Route = createFileRoute("/services/")({ head: () => ({ meta: [{ title: "Technology Services — Ikelex Technology" }, { name: "description", content: "Explore Ikelex software development, QR menus, hotel and POS systems, branding, digital growth, IT services and security." }, { property: "og:title", content: "Technology Services — Ikelex Technology" }, { property: "og:description", content: "Seven connected technology capabilities built for real business needs." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Services });
function Services() { return <div className="pt-28"><section className="relative overflow-hidden px-6 py-20 sm:py-28"><div className="absolute inset-0 ikelex-grid opacity-30"/><div className="relative mx-auto grid max-w-7xl items-end gap-14 lg:grid-cols-[1.05fr_.95fr]"><Reveal><p className="eyebrow">Seven connected capabilities</p><h1 className="mt-7 max-w-5xl text-balance text-6xl font-semibold uppercase leading-[.88] sm:text-8xl">Technology shaped around the business.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Strategy, design, implementation and support—connected around the work that needs to happen.</p></Reveal><ParallaxImage src={banner.url} alt="Abstract Ikelex technology system" className="aspect-[16/10] border border-border shadow-[var(--shadow-elevated)]"/></div></section><section className="dark-section py-28"><div className="mx-auto max-w-7xl px-6"><SectionHeading dark eyebrow="Service directory" title="Explore our capabilities" copy="Each service has its own approach, workflow and practical outcome."/><StaggerChildren className="mt-16 divide-y divide-ikelex-border border-y border-ikelex-border">{services.map((service, index) => <StaggerItem key={service.slug}><Link to="/services/$slug" params={{ slug: service.slug }} className="group grid items-center gap-5 py-8 sm:grid-cols-[60px_1fr_1fr_auto]"><span className="text-xs text-accent">0{index + 1}</span><h2 className="text-2xl font-semibold uppercase sm:text-4xl">{service.title}</h2><p className="text-sm leading-7 text-muted-foreground">{service.short}</p><span className="flex size-12 items-center justify-center border border-ikelex-border transition-colors group-hover:border-accent group-hover:text-accent"><ArrowUpRight className="size-5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></span></Link></StaggerItem>)}</StaggerChildren></div></section></div>; }
