import { createFileRoute, Link, notFound, redirect } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, MapPin, Phone } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { MagneticButton, ParallaxImage, SlideLeft, SlideRight, StaggerChildren, StaggerItem } from "@/components/animation-primitives";
import { Reveal, SectionHeading } from "@/components/ikelex";
import { serviceBySlug, serviceIcons } from "@/lib/site-data";
import { mergeServiceContent } from "@/lib/service-content";
import { getPublicContent } from "@/lib/public-content.functions";

export const Route = createFileRoute("/services/$slug")({
  loader: async ({ params }) => {
    const service = serviceBySlug(params.slug);
    if (!service) throw notFound();
    if (service.slug !== params.slug) throw redirect({ to: "/services/$slug", params: { slug: service.slug }, replace: true });
    const publicContent = await getPublicContent();
    return { serviceSlug: service.slug, publicContent };
  },
  head: ({ loaderData }) => {
    const service = loaderData ? serviceBySlug(loaderData.serviceSlug) : undefined;
    const editable = service && loaderData ? loaderData.publicContent.serviceContent.find((item) => item.slug === service.slug) : undefined;
    const content = service ? mergeServiceContent(service, editable) : undefined;
    return { meta: [
      { title: content ? `${content.title} — Ikelex Technology` : "Service — Ikelex Technology" },
      { name: "description", content: content?.heroDescription ?? "Ikelex Technology service." },
      { property: "og:title", content: content ? `${content.title} — Ikelex Technology` : "Ikelex Technology" },
      { property: "og:description", content: content?.heroDescription ?? "Practical technology solutions." },
      { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
    ] };
  }, component: ServicePage,
});

function ServicePage() {
  const { serviceSlug, publicContent } = Route.useLoaderData();
  const service = serviceBySlug(serviceSlug); if (!service) return null;
  const content = mergeServiceContent(service, publicContent.serviceContent.find((item) => item.slug === service.slug));
  const Icon = serviceIcons[content.iconKey];
  const imageByKey = new Map(publicContent.images.map((item) => [item.image_key, item]));
  const heroImage = imageByKey.get(`service-${service.slug}-hero`);
  const showcaseImage = imageByKey.get(`service-${service.slug}-showcase`); const secondaryImage = "secondaryImage" in service ? service.secondaryImage : undefined;
  const galleries = publicContent.images.filter((item) => item.image_key.startsWith(`service-${service.slug}-gallery-`) && item.url).sort((a, b) => a.image_key.localeCompare(b.image_key));
  const caseStudies = publicContent.caseStudies.filter((item) => item.service_slug === service.slug);
  const reviews = publicContent.reviews.filter((item) => item.service === service.title || item.service === content.title);
  const contact = publicContent.settings ?? { contact_person: "Alex Ikelia", phone: "+234 703 683 5166", address: "No. 22 Ehoro New Layout, Elelewon, Port Harcourt" };
  const imageSrc = heroImage?.url ?? service.image;
  return <div className="pt-28">
    <section className="relative overflow-hidden px-6 py-20 sm:py-28"><div className="absolute inset-0 ikelex-grid opacity-25"/><div className="relative mx-auto max-w-7xl"><Link to="/services" className="inline-flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground transition-colors hover:text-primary"><ArrowLeft className="size-4"/>All services</Link><div className="mt-14 grid items-end gap-14 lg:grid-cols-[1.05fr_.95fr]"><SlideLeft><Icon className="size-10 text-primary"/><p className="eyebrow mt-8">{content.eyebrow}</p><h1 className="mt-5 text-balance text-5xl font-semibold uppercase leading-[.9] sm:text-7xl lg:text-8xl">{content.title}</h1></SlideLeft><SlideRight><p className="max-w-2xl text-xl font-medium leading-9 text-foreground sm:text-2xl">{content.heroDescription}</p><MagneticButton className="mt-8"><Button variant="cinematic" size="lg" asChild><Link to="/contact">{content.heroCta}<ArrowUpRight/></Link></Button></MagneticButton></SlideRight></div></div></section>
    <section className="dark-section py-20"><div className="mx-auto max-w-7xl px-6"><ParallaxImage src={imageSrc} alt={heroImage?.alt_text ?? service.imageAlt} className="aspect-[16/8] w-full border border-ikelex-border shadow-[var(--shadow-elevated)] sm:aspect-[16/7]"/></div></section>
    <section className="py-28"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Overview" title={content.introTitle}/><Reveal><p className="max-w-3xl text-xl leading-9 text-muted-foreground">{content.introBody}</p></Reveal></div></section>
    {content.sections.map((section, sectionIndex) => <section key={section.title} className={sectionIndex % 2 ? "bg-surface-soft py-28" : "py-28"}><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Capabilities" title={section.title} {...(section.body ? { copy: section.body } : {})}/>{section.items.length > 0 && <StaggerChildren className="mt-14 grid gap-px border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{section.items.map((item, index) => <StaggerItem key={`${item.title}-${index}`} className="min-h-64 bg-background p-8 sm:p-10"><span className="text-xs font-bold text-primary">{String(index + 1).padStart(2, "0")}</span><h2 className="mt-12 text-2xl font-semibold uppercase">{item.title}</h2>{item.description && <p className="mt-4 text-sm leading-7 text-muted-foreground">{item.description}</p>}</StaggerItem>)}</StaggerChildren>}</div></section>)}
    {content.audiences.length > 0 && <section className="dark-section py-28"><div className="mx-auto max-w-7xl px-6"><SectionHeading dark eyebrow="Built for business" title={content.audienceTitle}/><StaggerChildren className="mt-14 grid gap-px border border-ikelex-border bg-ikelex-border sm:grid-cols-2 lg:grid-cols-4">{content.audiences.map((audience) => <StaggerItem key={audience} className="flex min-h-36 items-end bg-ikelex-navy-2 p-6"><p className="font-display text-lg font-semibold uppercase leading-6">{audience}</p></StaggerItem>)}</StaggerChildren></div></section>}
    {content.process.length > 0 && <section className="relative overflow-hidden bg-surface-soft py-28"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Process" title="A clear path from need to outcome"/><div className="relative mt-16"><div className="absolute left-5 top-5 hidden h-px w-[calc(100%-2.5rem)] bg-border lg:block"/><div className="grid gap-10 lg:grid-cols-6">{content.process.map((step, index) => <Reveal key={`${step.title}-${index}`} delay={index * .06}><div className="relative"><span className="relative z-10 grid size-10 place-items-center border border-primary bg-background text-xs font-bold text-primary">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-8 text-xl font-semibold uppercase">{step.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{step.description}</p></div></Reveal>)}</div></div></div></section>}
    {content.benefits.length > 0 && <section className="py-28"><div className="mx-auto grid max-w-7xl gap-16 px-6 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Business benefits" title="Designed for the way the work happens"/><div className="divide-y divide-border border-y border-border">{content.benefits.map((benefit, index) => <Reveal key={benefit.title} className="grid gap-4 py-7 sm:grid-cols-[48px_1fr]"><Check className="size-5 text-primary"/><div><h3 className="text-xl font-semibold uppercase">{benefit.title}</h3><p className="mt-2 leading-7 text-muted-foreground">{benefit.description}</p></div></Reveal>)}</div></div></section>}
    {(showcaseImage?.url || secondaryImage || galleries.length > 0) && <section className="dark-section py-24"><div className="mx-auto max-w-7xl px-6"><SectionHeading dark eyebrow="Service gallery" title="Technology in context"/><div className="mt-12 grid gap-5 md:grid-cols-2">{(showcaseImage?.url || secondaryImage) && <ParallaxImage src={showcaseImage?.url ?? secondaryImage ?? service.image} alt={showcaseImage?.alt_text ?? service.imageAlt} className="aspect-[4/3] border border-ikelex-border"/>}{galleries.map((image) => <ParallaxImage key={image.image_key} src={image.url ?? service.image} alt={image.alt_text} className="aspect-[4/3] border border-ikelex-border"/>)}</div></div></section>}
    {caseStudies.length > 0 && <section className="py-28"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Real work" title="Published case studies"/><div className="mt-14 grid gap-6 lg:grid-cols-2">{caseStudies.map((study) => <article key={study.id} className="border border-border bg-card p-8">{study.image_url && <img src={study.image_url} alt="" className="mb-7 aspect-[16/9] w-full object-cover"/>}<p className="eyebrow">Case study</p><h3 className="mt-5 text-3xl font-semibold uppercase">{study.title}</h3><p className="mt-5 leading-8 text-muted-foreground">{study.summary}</p><div className="mt-8 grid gap-6 border-t border-border pt-6 sm:grid-cols-3">{[["Challenge", study.challenge], ["Solution", study.solution], ["Outcome", study.outcome]].map(([label, value]) => <div key={label}><strong className="text-xs uppercase text-primary">{label}</strong><p className="mt-2 text-sm leading-6">{value}</p></div>)}</div></article>)}</div></div></section>}
    {reviews.length > 0 && <section className="bg-surface-soft py-24"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Customer voice" title="Genuine feedback"/><div className="mt-12 columns-1 gap-5 md:columns-2">{reviews.map((review) => <blockquote key={review.id} className="mb-5 break-inside-avoid border border-border bg-background p-8">{review.photo_url && <img src={review.photo_url} alt="" className="mb-6 size-12 rounded-full object-cover"/>}<p className="text-lg leading-8">“{review.review}”</p><footer className="mt-6 text-sm font-semibold">{review.customer_name}{review.company ? ` · ${review.company}` : ""}</footer></blockquote>)}</div></div></section>}
    <section className="py-28"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Service FAQ" title="Before we begin" copy="Pricing is tailored to the real scope. Contact Ikelex when you are ready to discuss the requirement."/><Accordion type="single" collapsible className="border-y border-border">{content.faqs.map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="text-left text-lg font-semibold">{question}</AccordionTrigger><AccordionContent className="text-base leading-8 text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="dark-section relative overflow-hidden py-28"><div className="absolute inset-0 ikelex-grid opacity-20"/><div className="relative mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[1fr_.55fr]"><Reveal><p className="eyebrow">{content.finalHeading}</p><h2 className="mt-6 max-w-4xl text-balance text-5xl font-semibold uppercase leading-[.94] sm:text-7xl">{content.finalTitle}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{content.finalBody}</p><div className="mt-9 flex flex-wrap gap-3"><Button variant="cinematic" size="lg" asChild><Link to="/contact">{content.primaryCta}<ArrowRight/></Link></Button><Button variant="outline" size="lg" asChild><Link to="/contact">{content.secondaryCta}</Link></Button></div></Reveal><Reveal className="border-l border-ikelex-border pl-8 lg:self-end"><p className="text-2xl font-semibold">{contact.contact_person}</p><p className="mt-1 text-sm text-muted-foreground">Ikelex Technology</p><a href={`tel:${contact.phone}`} className="mt-7 flex items-center gap-3 text-sm hover:text-accent"><Phone className="size-4"/>{contact.phone}</a><p className="mt-4 flex gap-3 text-sm leading-6 text-muted-foreground"><MapPin className="mt-1 size-4 shrink-0 text-accent"/>{contact.address}</p></Reveal></div></section>
  </div>;
}