import { Link, useRouterState } from "@tanstack/react-router";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowUpRight, ChevronDown, Mail, Menu, MessageCircle, Phone, X } from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import logo from "@/assets/ikelex-logo.png.asset.json";
import { Button } from "@/components/ui/button";
import { ScrollProgress, SlideUp } from "@/components/animation-primitives";
import { services } from "@/lib/site-data";
import { supabase } from "@/integrations/supabase/client";

const nav = [{ to: "/", label: "Home" }, { to: "/about", label: "About" }, { to: "/services", label: "Services" }, { to: "/faq", label: "FAQ" }, { to: "/contact", label: "Contact" }] as const;
const fallback = { phone: "+234 703 683 5166", whatsapp: "2347036835166", email: null as string | null, address: "No. 22 Ehoro New Layout, Elelewon, Port Harcourt" };

export function SiteShell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false); const [servicesOpen, setServicesOpen] = useState(false); const [contactOpen, setContactOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false); const [visible, setVisible] = useState(true); const [contact, setContact] = useState(fallback);
  const lastY = useRef(0); const path = useRouterState({ select: (s) => s.location.pathname }); const reduced = useReducedMotion();
  useEffect(() => { const onScroll = () => { const y = window.scrollY; setScrolled(y > 20); setVisible(y < 80 || y < lastY.current); lastY.current = y; }; onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { void supabase.from("site_settings").select("phone,whatsapp,email,address").limit(1).maybeSingle().then(({ data }) => { if (data) setContact(data); }); }, []);
  useEffect(() => { setOpen(false); setServicesOpen(false); }, [path]);
  if (path.startsWith("/admin") || path === "/auth") return <>{children}</>;
  return <div className="min-h-screen bg-background text-foreground">
    <ScrollProgress />
    <motion.header animate={{ y: visible || reduced ? 0 : -110 }} transition={{ duration: .35 }} className={`fixed left-1/2 top-3 z-50 w-[calc(100%-1.25rem)] max-w-7xl -translate-x-1/2 border transition-[background-color,border-color,box-shadow] duration-500 ${scrolled ? "border-ikelex-border bg-background/88 shadow-[var(--shadow-nav)] backdrop-blur-xl" : "border-ikelex-border/60 bg-background/72 backdrop-blur-lg"}`}>
      <nav className="flex h-16 items-center justify-between px-4 sm:px-6" aria-label="Main navigation">
        <Link to="/" aria-label="Ikelex Technology home"><img src={logo.url} alt="Ikelex Technology" className="h-9 w-auto" /></Link>
        <div className="hidden items-center gap-7 lg:flex">{nav.map((item) => item.to === "/services" ? <div key={item.to} className="relative" onMouseEnter={() => setServicesOpen(true)} onMouseLeave={() => setServicesOpen(false)}><Link to="/services" className="flex items-center gap-1 text-xs font-bold uppercase text-muted-foreground transition-colors hover:text-primary" activeProps={{ className: "text-primary" }}>Services <ChevronDown className="size-3"/></Link><AnimatePresence>{servicesOpen && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 8 }} className="absolute left-1/2 top-6 w-[680px] -translate-x-1/2 border border-border bg-popover p-3 shadow-[var(--shadow-nav)]"><div className="grid grid-cols-2">{services.map((service) => <Link key={service.slug} to="/services/$slug" params={{ slug: service.slug }} className="group flex gap-3 p-4 transition-colors hover:bg-secondary"><service.icon className="mt-0.5 size-5 text-primary"/><span><strong className="block text-sm font-semibold text-foreground">{service.title}</strong><small className="mt-1 block text-xs leading-5 text-muted-foreground">{service.short}</small></span></Link>)}</div></motion.div>}</AnimatePresence></div> : <Link key={item.to} to={item.to} activeOptions={{ exact: item.to === "/" }} className="text-xs font-bold uppercase text-muted-foreground transition-colors hover:text-primary" activeProps={{ className: "text-primary" }}>{item.label}</Link>)}<Button variant="cinematic" size="lg" asChild><Link to="/contact">Let's work together <ArrowUpRight /></Link></Button></div>
        <Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen((value) => !value)} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open}>{open ? <X /> : <Menu />}</Button>
      </nav>
      <AnimatePresence>{open && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden border-t border-border bg-background lg:hidden"><div className="p-4">{nav.map((item, index) => <motion.div key={item.to} initial={{ opacity: 0, x: 14 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .04 }}><Link to={item.to} className="flex items-center justify-between border-b border-border py-4 font-display text-lg font-semibold uppercase">{item.label}<ArrowUpRight className="size-4 text-primary"/></Link>{item.to === "/services" && <div className="grid grid-cols-1 border-b border-border py-2 sm:grid-cols-2">{services.map((service) => <Link key={service.slug} to="/services/$slug" params={{ slug: service.slug }} className="py-2 text-sm text-muted-foreground">{service.title}</Link>)}</div>}</motion.div>)}</div></motion.div>}</AnimatePresence>
    </motion.header>
    <main>{children}</main>
    <GlobalCTA />
    <footer className="dark-section relative overflow-hidden border-t border-ikelex-border py-10">
      <div className="absolute inset-0 ikelex-grid opacity-10"/>
      <div aria-hidden className="pointer-events-none absolute -left-24 top-0 size-[26rem] animate-[liquid-blob-a_16s_ease-in-out_infinite] rounded-full bg-ikelex-blue-bright/25 blur-[90px]"/>
      <div aria-hidden className="pointer-events-none absolute -right-16 bottom-0 size-[22rem] animate-[liquid-blob-b_19s_ease-in-out_infinite] rounded-full bg-ikelex-cyan/20 blur-[90px]"/>
      <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} className="liquid-glass relative mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-white/15 bg-ikelex-navy/45 p-7 shadow-[var(--shadow-elevated)] backdrop-blur-2xl sm:p-10">
        <div aria-hidden className="pointer-events-none absolute inset-x-6 top-0 h-px bg-gradient-to-r from-transparent via-white/50 to-transparent"/>
        <div className="grid gap-12 lg:grid-cols-[1.4fr_.7fr_1fr]"><div><img src={logo.url} alt="Ikelex Technology" className="h-12 w-auto"/><p className="mt-6 max-w-md text-sm leading-7 text-muted-foreground">Digital systems, products and infrastructure built around real business needs.</p></div><div><p className="eyebrow">Navigate</p>{nav.map((item) => <Link key={item.to} to={item.to} className="mt-4 block text-sm text-muted-foreground transition-colors hover:text-accent">{item.label}</Link>)}</div><div><p className="eyebrow">Contact</p><a href={`tel:${contact.phone}`} className="mt-4 block text-sm text-muted-foreground hover:text-accent">{contact.phone}</a>{contact.email && <a href={`mailto:${contact.email}`} className="mt-3 block text-sm text-muted-foreground hover:text-accent">{contact.email}</a>}<p className="mt-3 max-w-xs text-sm leading-6 text-muted-foreground">{contact.address}</p></div></div>
        <div className="relative mt-14 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-muted-foreground sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} Ikelex Technology</span><span>Built for what comes next.</span></div>
      </motion.div>
    </footer>
    <div className="fixed bottom-5 right-5 z-50 flex flex-col items-end gap-2"><AnimatePresence>{contactOpen && <motion.div initial={{ opacity: 0, y: 14, scale: .96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 14, scale: .96 }} className="w-60 border border-border bg-popover p-2 shadow-[var(--shadow-nav)]"><a href={`https://wa.me/${contact.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="flex items-center gap-3 px-3 py-3 text-sm hover:bg-secondary"><MessageCircle className="size-4 text-contact"/>WhatsApp</a>{contact.email && <a href={`mailto:${contact.email}`} className="flex items-center gap-3 px-3 py-3 text-sm hover:bg-secondary"><Mail className="size-4 text-primary"/>Email Ikelex</a>}<a href={`tel:${contact.phone}`} className="flex items-center gap-3 px-3 py-3 text-sm hover:bg-secondary"><Phone className="size-4 text-primary"/>Call Ikelex</a></motion.div>}</AnimatePresence><Button onClick={() => setContactOpen((value) => !value)} size="icon" className="size-14 rounded-full bg-contact text-contact-foreground shadow-[var(--shadow-nav)] hover:bg-contact/90" aria-label="Contact Ikelex" aria-expanded={contactOpen}><MessageCircle className="size-6"/></Button></div>
  </div>;
}

export function GlobalCTA() { return <section className="dark-section relative overflow-hidden py-28"><div className="absolute inset-0 ikelex-grid opacity-20"/><div className="relative mx-auto max-w-7xl px-6"><SlideUp><p className="eyebrow">Start a conversation</p><div className="mt-6 grid items-end gap-8 lg:grid-cols-[1fr_auto]"><h2 className="max-w-4xl text-balance text-5xl font-semibold uppercase leading-[.92] sm:text-7xl">Ready to build something better?</h2><Button variant="cinematic" size="lg" asChild><Link to="/contact">Request a quote <ArrowUpRight/></Link></Button></div></SlideUp></div></section>; }
export function Reveal({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) { return <SlideUp className={className} delay={delay}>{children}</SlideUp>; }
export function SectionHeading({ eyebrow, title, copy, dark = false }: { eyebrow: string; title: string; copy?: string; dark?: boolean }) { return <Reveal className="max-w-4xl"><p className="eyebrow">{eyebrow}</p><h2 className={`mt-5 text-balance text-4xl font-semibold uppercase leading-[.96] sm:text-6xl lg:text-7xl ${dark ? "text-ikelex-white" : "text-foreground"}`}>{title}</h2>{copy && <p className="mt-6 max-w-2xl text-base leading-8 text-muted-foreground">{copy}</p>}</Reveal>; }
