import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { services, type ContentItem, type ContentSection, type IconKey, type ProcessStep } from "@/lib/site-data";
import { mergeServiceContent } from "@/lib/service-content";
import type { Json, Tables } from "@/integrations/supabase/types";

type Row = Tables<"service_content">;
const iconOptions: Array<{ value: IconKey; label: string }> = [{ value: "code", label: "Software" }, { value: "qr-code", label: "QR code" }, { value: "computer", label: "Computer" }, { value: "hotel", label: "Hotel/POS" }, { value: "palette", label: "Design" }, { value: "growth", label: "Growth" }, { value: "security", label: "Security" }];
const itemLines = (items: readonly ContentItem[]) => items.map((item) => `${item.title} | ${item.description}`).join("\n");
const sectionLines = (items: readonly ContentSection[]) => items.map((section) => [`# ${section.title}`, section.body ? `> ${section.body}` : "", ...section.items.map((item) => `${item.title} | ${item.description}`)].filter(Boolean).join("\n")).join("\n\n");
const processLines = (items: readonly ProcessStep[]) => items.map((item) => `${item.title} | ${item.description}`).join("\n");
const faqLines = (items: readonly (readonly [string, string])[]) => items.map(([question, answer]) => `${question} | ${answer}`).join("\n");
const parsePairs = (value: string): ContentItem[] => value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [title, ...description] = line.split("|"); return { title: title?.trim() ?? "", description: description.join("|").trim() }; }).filter((item) => item.title);
const parseSections = (value: string): ContentSection[] => value.split(/^# /m).map((block) => block.trim()).filter(Boolean).map((block) => { const [title = "", ...source] = block.split("\n"); const rest = [...source]; const bodyLine = rest[0]?.startsWith("> ") ? rest.shift() : undefined; const section = { title: title.trim(), items: parsePairs(rest.join("\n")) }; return bodyLine ? { ...section, body: bodyLine.slice(2).trim() } : section; });

export function ServiceContentEditor() {
  const [rows, setRows] = useState<Row[]>([]); const [slug, setSlug] = useState<string>(services[0].slug); const [notice, setNotice] = useState("");
  useEffect(() => { void supabase.from("service_content").select("*").then(({ data }) => setRows(data ?? [])); }, []);
  const service = services.find((item) => item.slug === slug) ?? services[0]; const row = rows.find((item) => item.slug === service.slug); const content = mergeServiceContent(service, row);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice("Saving…"); const fd = new FormData(event.currentTarget); const payload = { slug: service.slug, eyebrow: String(fd.get("eyebrow")), title: String(fd.get("title")), hero_description: String(fd.get("hero_description")), intro_title: String(fd.get("intro_title")), intro_body: String(fd.get("intro_body")), sections: parseSections(String(fd.get("sections"))) as unknown as Json, audience_title: String(fd.get("audience_title")), audiences: String(fd.get("audiences")).split("\n").map((item) => item.trim()).filter(Boolean) as Json, process: parsePairs(String(fd.get("process"))) as Json, benefits: parsePairs(String(fd.get("benefits"))) as Json, faqs: parsePairs(String(fd.get("faqs"))).map((item) => [item.title, item.description]) as Json, hero_cta: String(fd.get("hero_cta")), final_heading: String(fd.get("final_heading")), final_title: String(fd.get("final_title")), final_body: String(fd.get("final_body")), primary_cta: String(fd.get("primary_cta")), secondary_cta: String(fd.get("secondary_cta")), icon_key: String(fd.get("icon_key")) }; const result = await supabase.from("service_content").upsert(payload, { onConflict: "slug" }).select("*").single(); if (result.error) { setNotice("The service content could not be saved."); return; } setRows((current) => [...current.filter((item) => item.slug !== service.slug), result.data]); setNotice("Service page saved."); }
  return <div className="mt-6"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{services.map((item) => <Button key={item.slug} type="button" variant={item.slug === slug ? "default" : "outline"} onClick={() => { setSlug(item.slug); setNotice(""); }} className="h-auto min-h-11 whitespace-normal text-left">{item.title}</Button>)}</div><form key={`${slug}-${row?.updated_at ?? "default"}`} onSubmit={submit} className="mt-8 grid gap-5 md:grid-cols-2">
    <Field label="Service title"><Input name="title" defaultValue={content.title} required maxLength={140}/></Field><Field label="Eyebrow"><Input name="eyebrow" defaultValue={content.eyebrow} required maxLength={80}/></Field><Field label="Service icon"><select name="icon_key" defaultValue={content.iconKey} className="h-10 w-full border border-input bg-background px-3 text-sm">{iconOptions.map((icon) => <option key={icon.value} value={icon.value}>{icon.label}</option>)}</select></Field><Field label="Hero button"><Input name="hero_cta" defaultValue={content.heroCta} required maxLength={60}/></Field>
    <Field label="Hero description" wide><Textarea name="hero_description" defaultValue={content.heroDescription} required rows={5}/></Field><Field label="Overview heading"><Input name="intro_title" defaultValue={content.introTitle} required/></Field><Field label="Audience heading"><Input name="audience_title" defaultValue={content.audienceTitle} required/></Field><Field label="Overview copy" wide><Textarea name="intro_body" defaultValue={content.introBody} required rows={6}/></Field>
    <Field label="Feature sections" hint="Start each section with #, optional introduction with >, then Title | Description." wide><Textarea name="sections" defaultValue={sectionLines(content.sections)} rows={14}/></Field><Field label="Audience list" hint="One audience per line"><Textarea name="audiences" defaultValue={content.audiences.join("\n")} rows={9}/></Field><Field label="Process" hint="One step per line: Title | Description"><Textarea name="process" defaultValue={processLines(content.process)} rows={9}/></Field><Field label="Benefits" hint="One benefit per line: Title | Description"><Textarea name="benefits" defaultValue={itemLines(content.benefits)} rows={9}/></Field><Field label="FAQs" hint="One FAQ per line: Question | Answer"><Textarea name="faqs" defaultValue={faqLines(content.faqs)} rows={9}/></Field>
    <Field label="Final eyebrow"><Input name="final_heading" defaultValue={content.finalHeading} required/></Field><Field label="Final heading"><Input name="final_title" defaultValue={content.finalTitle} required/></Field><Field label="Final copy" wide><Textarea name="final_body" defaultValue={content.finalBody} required rows={4}/></Field><Field label="Primary button"><Input name="primary_cta" defaultValue={content.primaryCta} required/></Field><Field label="Secondary button"><Input name="secondary_cta" defaultValue={content.secondaryCta} required/></Field><div className="flex items-center gap-4 md:col-span-2"><Button type="submit"><Save/>Save service page</Button>{notice && <p className="text-sm text-muted-foreground" role="status">{notice}</p>}</div>
  </form></div>;
}
function Field({ label, hint, wide, children }: { label: string; hint?: string; wide?: boolean; children: ReactNode }) { return <div className={wide ? "md:col-span-2" : ""}><Label className="mb-2 block">{label}</Label>{children}{hint && <p className="mt-2 text-xs leading-5 text-muted-foreground">{hint}</p>}</div>; }